name: Build And Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} ghcr.io
          docker build -t ${{ secrets.DOCKER_URL }} .
          docker push ${{ secrets.DOCKER_URL }}
          echo "Build and push completed!"
